### ISSUE TITLE
Error: Command failed: at ChildProcess.exithandler

### ISSUE THREAD

**Issue by autisid** [oauth-io/oauth-phonegap#43]
I got this error when i trying to add the plugin.

Fetching plugin "https://github.com/oauth-io/oauth-phonegap" via git clone
Error: Command failed:
    at ChildProcess.exithandler (child_process.js:648:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:756:16)
    at Socket.<anonymous> (child_process.js:969:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:465:12)

**Comment by bumpmann** [comment]
This does not looks like related to oauth-phonegap. You should try to update cordova/phonegap/git.
